# fly.toml app configuration file generated for farmtotabserver on 2024-04-08T23:06:38+05:30
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'farmtotabserver'
primary_region = 'mia'

[build]

[http_service]
  internal_port = 1999
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '512mb'
  cpu_kind = 'shared'
  cpus = 1
